-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 15, 2022 at 03:52 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Database: `data`
--
CREATE DATABASE IF NOT EXISTS `data` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `data`;

-- --------------------------------------------------------

--
-- Table structure for table `tblproduct`
--
-- Creation: May 15, 2022 at 01:52 AM
-- Last update: May 15, 2022 at 01:52 AM
--

CREATE TABLE IF NOT EXISTS `tblproduct` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `brand` varchar(255) DEFAULT NULL,
  `product_image` varchar(255) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `product_description` longtext DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `customer` varchar(255) DEFAULT NULL,
  `product_id_number` varchar(255) DEFAULT NULL,
  `product_status` varchar(255) DEFAULT NULL,
  `date_of_purchase` datetime DEFAULT current_timestamp(),
  `payment_method` varchar(255) DEFAULT NULL,
  `shippingfee` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=314 DEFAULT CHARSET=utf8mb4;

--
-- RELATIONSHIPS FOR TABLE `tblproduct`:
--

--
-- Dumping data for table `tblproduct`
--

INSERT INTO `tblproduct` (`id`, `brand`, `product_image`, `product_name`, `product_description`, `price`, `customer`, `product_id_number`, `product_status`, `date_of_purchase`, `payment_method`, `shippingfee`) VALUES
(44, 'acer', 'admin/image/aspire3_314-35_sv_01a_front_1.jpg', 'Aspire A314-35-C733 I Best For Student L Intel Celeron', 'Windows 11 Home\r\nIntel UHD Graphics\r\n36.7 Wh 2-cell Li-ion battery\r\nBattery life up to 8 hours\r\n2 Years Warranty\r\n14\" HD 1366 x 768 resolution\r\nBe the first to review this product', '₱20,899.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(45, 'acer', 'admin/image/aspire3_314-35_sv_01a_front_2.jpg', 'Aspire 3 A314-35-C6GV Intel Celeron', 'Windows 11 Home\r\nIntel® Celeron® dual-core processor\r\n4 GB of DDR4 system memory\r\n256GB NVMe SSD\r\n15.6\"\r\nIntel® UHD Graphics\r\n2 year warranty\r\nBe the first to review this product', '₱21,999.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(46, 'acer', 'admin/image/aspire_p5n9_front_1.jpg', 'Aspire 3 L A315-35-P5N9 L Intel® Pentium', 'Windows 11 Home\r\n8 GB of DDR4\r\nupgradable to 16GB\r\n256GB NVMe SSD\r\nIntel® UHD Graphics\r\nIntel® Pentium® Silver N6000 Processor\r\n2 years warranty\r\nBe the first to review this product', '₱23,749.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(47, 'acer', 'admin/image/aspire3_314-35_sv_01a_front.jpg', 'Aspire A314-35-P0DC I Best For Student L Intel® Pentium®', 'Windows 11 Home\r\nIntel Pentium Silver N6000\r\n14\" HD 1366 x 768 resolution\r\nIntel UHD Graphics\r\n8GB LPDDR4 SDRAM, 256 GB NVMe M.2\r\nBattery up to 8 hours\r\nBe the first to review this product', '₱23,749.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(48, 'asus', 'admin/image/uploaded_696838c5debd9d2e43ab4713a7e149e2.jpg', 'ASUS VivoBook 15 2021 Price List May, 2022 & Specs in Philippines', 'Running on Windows 10, ASUS’s VivoBook 15 2021 has a screen resolution of 1920 x 1080pixels. Weighs only 1.9kg, this ASUS laptop has a HDD, and is made from Aluminium. Scroll down to view the full specs of ASUS VivoBook 15 2021 now!', '₱ 37,561.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(49, 'asus', 'admin/image/uploaded_675c734465fa78c43706a015ebdc16b2.jpg', 'ASUS ROG Zephyrus G14 GA401 Price List May, 2022 & Specs in Philippines', 'ASUS’s ROG Zephyrus G14 GA401 is a Windows 10 Pro laptop. In terms of display, it has a screen resolution of 2560 x 1440pixels. It weighs only 1.7kg and is made from Magnesium Alloy. Scroll down below to compare the price of this ASUS laptop and check out', '₱ 41,000.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(50, 'asus', 'admin/image/uploaded_f229cab2c9b2f84657959203eecfa517.jpg', 'ASUS ROG Strix G15 Price List May, 2022 & Specs in Philippines', 'ASUS’s ROG Strix G15 is a Windows 10 Home (64-bit) laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.39kg and is made from Plastic. Scroll down below to compare the price of this ASUS laptop and check out its s', ' ₱ 84,945.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(51, 'asus', 'admin/image/uploaded_0162babaaf613a47b98d7b30bf4eaf69.jpg', 'ASUS TUF Gaming F15 Price List May, 2022 & Specs in Philippines', 'ASUS’s TUF Gaming F15 is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.6kg and is made from Aluminium. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 44,745.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(52, 'dell', 'admin/image/uploaded_dd8db952045f54ad9cb9d610673c007a.jpg', 'Dell Inspiron 15 3000 Price List May, 2022 & Specs in Philippines', 'Dell has always been a favourite both for desktops and laptops. For office, home and leisure, Dell has become a name we are all familiar with. The reason we love Dell is mainly its affordability and user-friendly nature. Programmed for excellence, Dell’s ', '₱ 28,696.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(53, 'dell', 'admin/image/uploaded_9ab9f7ee1ab7ab499c985da4e6e552be.jpg', 'DELL XPS 15 Price List May, 2022 & Specs in Philippines', 'DISPLAY\r\nScreen Size	15\"\r\nScreen Resolution	3840 x 2400pixels\r\nScreen Technology	IPS\r\nBATTERY\r\nBattery Life	8h\r\nDESIGN\r\nWeight	2.05kg\r\nBody Material	Aluminium\r\nGRAPHICS\r\nGraphic Card	Nvidia GeForce GTX 1650 Ti\r\nSTORAGE\r\nStorage Type	SSD\r\nCAMERA\r\nWebcam Re', '₱ 113,344.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(54, 'dell', 'admin/image/uploaded_fdc5495ca3ca2fc8d7c9d95243bde7e1.jpg', 'Dell Inspiron 15 3000 Intel Core i3-4005 15.6-inch 4GB Price List May, 2022 & Specs in Philippines', 'Dell’s Inspiron 15 3000 is a Windows 8 laptop that is powered by Intel Integrated HD Graphics 520 graphics card. The Dell laptop features an 00 and 7h of battery life, while its body is made of Plastic. Weighing only 2.2kg, the Dell laptop is ultra-portab', '₱ 33,841.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(55, 'dell', 'admin/image/uploaded_d70915bce34ed81f1d9896b3e4b85e8a.jpg', 'Dell Alienware Area-51m Price List May, 2022 & Specs in Philippines', 'Dell’s Alienware Area-51m is a SSD laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 4.7kg and is made from Aluminium. Scroll down below to compare the price of this Dell laptop and check out its specs!', ' ₱ 21,900.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(56, 'hp', 'admin/image/uploaded_1b022279c0dec631967a6e16898c8f03.jpg', 'HP Pavilion 15 Price List May, 2022 & Specs in Philippines', 'The HP Pavilion 15 is a 15.6\" LED display touchscreen laptop that operates on Windows 10. It is powered by NVIDIA and is supported by 512GB SSD with up to 4GB RAM, while its battery life can last up to 14h. With HP Pavilion 15, you can stay productive and', ' ₱ 48,120.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(57, 'hp', 'admin/image/uploaded_086b95e3f9d57f7a74d532e923b16641.jpg', 'HP Spectre x360 Price List May, 2022 & Specs in Philippines', 'Made by HP and co-designed by Microsoft, the HP Spectre X360 presents an array of attractive specs for any user. Sleek and presentable, the HP Spectre X360 is visually appealing with the best of goodies on the inside. Keeping up with the times, the HP Spe', '₱ 125,048.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(58, 'hp', 'admin/image/uploaded_6d136ae5046ca60006487a5209083a76.jpg', 'HP Envy x360 13 Price List May, 2022 & Specs in Philippines', 'HP’s Envy x360 13 is a Windows 10 laptop that is powered by AMD Radeon Vega 8 Graphics graphics card. The HP laptop features an SSD and 5h of battery life, while its body is made of Aluminium. Weighing only 1.2kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 66,209.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(59, 'hp', 'admin/image/uploaded_5ed794ae83ec1918084423d28f632677.jpg', 'HP Victus 16 Price List May, 2022 & Specs in Philippines', 'HP’s Victus 16 is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.4kg and is made from Aluminium. Scroll down below to compare the price of this HP laptop and check out its specs!\r\n', '₱ 52,748.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(60, 'lenovo', 'admin/image/uploaded_bbfa4bd7e0c7b1b6a84b0425313c757c.jpg', 'Lenovo IdeaPad 3 14 Price List May, 2022 & Specs in Philippines', 'Lenovo’s IdeaPad 3 14 is a Windows 10 Home laptop that is powered by Intel UHD G1 graphics card. The Lenovo laptop features an SSD and 4h of battery life, while its body is made of Plastic. Weighing only 1.6kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 23,478.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(61, 'lenovo', 'admin/image/uploaded_afe201a9cc6792af94aa5d4cb8402bbb.jpg', 'Lenovo Legion 5 Gaming Laptop Price List May, 2022 & Specs in Philippines', 'Lenovo’s Legion 5 Gaming Laptop is a Windows 10 Home laptop that is powered by NVIDIA GeForce GTX 1650Ti 4GB graphics card. The Lenovo laptop features an SSD and 5h of battery life, while its body is made of Plastic. Weighing only 2.5kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 89,748.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(62, 'lenovo', 'admin/image/uploaded_a38aefc84253ba2194b0d0b512d8334a.jpg', 'Lenovo Legion 7 Price List May, 2022 & Specs in Philippines', 'DISPLAY\r\nScreen Size	16\"\r\nScreen Resolution	2560 x 1600pixels\r\nScreen Technology	IPS\r\nSTORAGE\r\nStorage	2000GB\r\nStorage Type	SSD\r\nMEMORY\r\nRAM	32GB\r\nRAM Type	GDDR6\r\nBATTERY\r\nBattery Life	8h\r\nDESIGN\r\nWeight	2.5kg\r\nGRAPHICS\r\nGraphic Card	NVIDIA®GeForce RTX™ 3080\r\nCAMERA\r\nWebcam Resolution	HD\r\nFEATURES\r\nBacklit Keyboard	Yes\r\nFingerprint Reader	No\r\nTouch Screen	No\r\nCONNECTOR PORTS\r\nUSB Type-C	Yes\r\nThunderbolt	Yes\r\nUSB 3.0	No\r\nDisplayPort	Yes\r\nUSB	Yes\r\nCard Reader	No\r\nHDMI	Yes\r\nHeadphone Jack	Yes\r\nPLATFORM\r\nOS	Windows 10 Pro\r\nCONNECTION\r\nWi-Fi Standard	802.11 ax', ' ₱ 139,995.00', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(63, 'lenovo', 'admin/image/uploaded_bda0c284d3b07d03c909458c8315f076.jpg', 'Lenovo ThinkPad X1 Carbon Price List May, 2022 & Specs in Philippines', 'If you are looking for a suitable laptop for your business travels, Lenovo ThinkPad X1 Carbon is the perfect candidate because it is one of the most business-centric laptops in the market. Powerful and portable at the same time, you can never go wrong with Lenovo ThinkPad X1 Carbon. Read more about Lenovo ThinkPad X1 Carbon Philippines here below to find out.', '₱ 66,695.43', NULL, NULL, NULL, '2022-05-12 19:15:56', NULL, NULL),
(65, 'asus', 'admin/image/asus-Asus TUF Gaming FX505DT.jpg', 'Asus TUF Gaming FX505DT Price List May, 2022 & Specs in Philippines', 'Asus�s TUF Gaming FX505DT is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.3kg and is made from Aluminium. Scroll down below to compare the price of this Asus laptop and check out its specs!', '₱ 49,329.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(66, 'asus', 'admin/image/asus-ASUS VivoBook Flip 14.jpg', 'ASUS VivoBook Flip 14 Price List May, 2022 & Specs in Philippines', 'ASUS�s VivoBook Flip 14 is a Windows 10 laptop that is powered by Intel UHD Graphics 620 graphics card. The ASUS laptop features an SSD and 24h of battery life, while its body is made of Aluminium. Weighing only 1.5kg, the ASUS laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 48,068.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(67, 'asus', 'admin/image/asus-Asus X407MA.jpg', 'Asus X407MA Price List May, 2022 & Specs in Philippines', 'Asus�s X407MA is a Windows 10 Home laptop that is powered by Intel UHD Graphics 605 graphics card. The Asus laptop features an SATA and 6h of battery life, while its body is made of Aluminium. Weighing only 1.55kg, the Asus laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Asus laptop and check out its specs!', '₱ 18,000.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(68, 'asus', 'admin/image/asus-ASUS TUF Dash F15.jpg', 'ASUS TUF Dash F15 Price List May, 2022 & Specs in Philippines', 'ASUS�s TUF Dash F15 is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2kg and is made from Plastic. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 48,145.38', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(69, 'asus', 'admin/image/asus-ASUS ROG Strix G17.jpg', 'ASUS ROG Strix G17 Price List May, 2022 & Specs in Philippines', 'ASUS�s ROG Strix G17 is a Windows 10 Home (64-bit) laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.39kg and is made from Plastic. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 77,990.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(70, 'asus', 'admin/image/asus-Asus ROG Flow X13.jpg', 'Asus ROG Flow X13 Price List May, 2022 & Specs in Philippines', 'Asus�s ROG Flow X13 is a Windows 10 Pro laptop. In terms of display, it has a screen resolution of 3840 x 2400pixels. It weighs only 1.3kg and is made from Magnesium Alloy. Scroll down below to compare the price of this Asus laptop and check out its specs', '₱ 96,999.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(71, 'asus', 'admin/image/asus-Asus Chromebook C423NA.jpg', 'Asus Chromebook C423NA Price List May, 2022 & Specs in Philippines', 'The Asus Chromebook C423NA is a 14\" IPS display touchscreen laptop that operates on Chrome OS. It is powered by Integrated Intel CPU and is supported by 32GB eMMC with up to 4GB RAM, while its battery life can last up to 10h. With Asus Chromebook C423NA, you can stay productive and focus on your work; available with the cheapest price at PHP 15676 at iPrice today!', '₱ 15,676.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(72, 'asus', 'admin/image/asus-ASUS VivoBook S14.jpg', 'ASUS VivoBook S14 Price List May, 2022 & Specs in Philippines', 'Running on Windows 10, ASUS�s VivoBook S14 has a screen resolution of 1920 x 1080pixels. Weighs only 1.4kg, this ASUS laptop has a HDD+SSD/eMMC, and is made from Aluminium. Scroll down to view the full specs of ASUS VivoBook S14 now!', '₱ 57,008.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(73, 'asus', 'admin/image/asus-Asus ZenBook Pro Duo UX581.jpg', 'Asus ZenBook Pro Duo UX581 Price List May, 2022 & Specs in Philippines\r\n', 'Asus�s ZenBook Pro Duo UX581 is a Windows 10 Home laptop that is powered by Nvidia GeForce RTX 2060 graphics card. The Asus laptop features an SSD and 2h of battery life, while its body is made of Aluminium. Weighing only 2.5kg, the Asus laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Asus laptop and check out its specs!', '₱ 265,767.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(74, 'asus', 'admin/image/asus-ASUS Expertbook B5 Flip.jpg', 'ASUS Expertbook B5 Flip Price List May, 2022 & Specs in Philippines', 'ASUS�s Expertbook B5 Flip is a Windows 10 Pro laptop that is powered by Intel Iris X? Graphics graphics card. The ASUS laptop features an SSD and 12h of battery life, while its body is made of Magnesium Alloy. Weighing only 1kg, the ASUS laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 32,745.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(75, 'asus', 'admin/image/asus-ASUS M515.jpg', 'ASUS M515 Laptop Price List May, 2022 & Specs in Philippines', 'ASUS�s M515 Laptop is a Windows 10 Pro laptop that is powered by Radeon� Vega 8 graphics card. The ASUS laptop features an SSD and 16h of battery life, while its body is made of Aluminium. Weighing only 1.8kg, the ASUS laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 29,995.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(76, 'asus', 'admin/image/asus-ASUS TUF Gaming F17.jpg', 'ASUS TUF Gaming F17 Price List May, 2022 & Specs in Philippines', 'ASUS�s TUF Gaming F17 is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.6kg and is made from Aluminium. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 66,723.42', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(77, 'asus', 'admin/image/asus-Asus Zenbook 14 Ultrabook.jpg', 'Asus Zenbook 14 Ultrabook Price List May, 2022 & Specs in Philippines', 'Running on Windows 10 Home, Windows 10 Pro, Asus�s Zenbook 14 Ultrabook has a screen resolution of 1080 x 1920pixels. Weighs only 1.39kg, this Asus laptop has a SSD, and is made from Steel. Scroll down to view the full specs of Asus Zenbook 14 Ultrabook now!', '₱ 49,990.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(78, 'asus', 'admin/image/asus-ASUS ZenBook Duo 14 UX482.jpg', 'ASUS ZenBook Duo 14 UX482 Price List May, 2022 & Specs in Philippines', 'ASUS�s ZenBook Duo 14 UX482 is a Windows 10 Home laptop that is powered by Intel Iris Xe Graphics graphics card. The ASUS laptop features an SSD and 10h of battery life, while its body is made of Aluminium. Weighing only 1.6kg, the ASUS laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 77,176.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(79, 'asus', 'admin/image/asus-ASUS ROG GL502VM.jpg', 'ASUS ROG GL502VM Price List May, 2022 & Specs in Philippines', 'ASUS�s ROG GL502VM is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 3840 x 2160pixels. It weighs only 2.2kg and is made from Aluminium. Scroll down below to compare the price of this ASUS laptop and check out its specs!', '₱ 161,610.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(80, 'acer', 'admin/image/acer-Acer Nitro 5.jpg', 'Acer Nitro 5 Price List May, 2022 & Specs in Philippines', 'Acer�s Nitro 5 is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.48kg and is made from Plastic. Scroll down below to compare the price of this Acer laptop and check out its specs! Read more', '₱ 49,898.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(81, 'acer', 'admin/image/acer-Acer Aspire 3.jpg', 'Acer Aspire 3 Price List May, 2022 & Specs in Philippines', 'Acer�s Aspire 3 is a Windows 10 Home laptop that is powered by Intel HD Graphics 520 graphics card. The Acer laptop features an SSD and 6.5h of battery life, while its body is made of Plastic. Weighing only 1.9kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs! Read more', '₱ 19,550.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(82, 'acer', 'admin/image/acer-Acer Predator Helios 300.jpg', 'Acer Predator Helios 300 PH315-54 Price List May, 2022 & Specs in Philippines', 'Acer�s Predator Helios 300 PH315-54 is a Windows 10 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.9kg and is made from Aluminium. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 53,899.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(83, 'acer', 'admin/image/acer-Acer Aspire 3 8GB.jpg', 'Acer Aspire 3 8GB Intel Pentium 256GB Price List May, 2022 & Specs in Philippines', 'Acer�s Aspire 3 is a Windows 10 Home laptop that is powered by Intel HD Graphics 520 graphics card. The Acer laptop features an SSD and 6.5h of battery life, while its body is made of Plastic. Weighing only 1.9kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 22,890.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(84, 'acer', 'admin/image/acer-Acer Chromebook Spin 713.jpg', 'Acer Chromebook Spin 713 Price List May, 2022 & Specs in Philippines', 'Acer�s Chromebook Spin 713 is a Chrome OS laptop that is powered by Intel� UHD Graphics graphics card. The Acer laptop features an SSD and 10h of battery life, while its body is made of Aluminium. Weighing only 1.37kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 29,426.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(85, 'acer', 'admin/image/acer-Acer Spin 5.jpg', 'Acer Spin 5 Price List May, 2022 & Specs in Philippines', 'Acer�s Spin 5 is a Windows 10 Home laptop that is powered by Intel UHD Graphics 620 graphics card. The Acer laptop features an SATA and 11h of battery life, while its body is made of Steel. Weighing only 1.58kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 45,895.61', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(86, 'acer', 'admin/image/acer-Acer Aspire One.jpg', 'Acer Aspire One Price List May, 2022 & Specs in Philippines', 'The Acer Aspire One is a 10.1-inch netbook that can do all the office and school paper basics smoothly. From MS Office to moderate browsing and light gaming. The Acer Aspire One provides convenience and performance for all your basic computer needs. Check out its main features right here!', '₱ 29,176.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(87, 'acer', 'admin/image/acer-Acer Swift 1.jpg', 'Acer Swift 1 Price List May, 2022 & Specs in Philippines', 'Acer�s Swift 1 is a Windows 10 laptop that is powered by Intel graphics card. The Acer laptop features an SSD and 17h of battery life, while its body is made of Aluminium. Weighing only 1.3kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 28,838.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(88, 'acer', 'admin/image/acer-Acer Chromebook Spin 11.jpg', 'Acer Chromebook Spin 11 Price List May, 2022 & Specs in Philippines', 'Acer�s Chromebook Spin 11 is a Chrome OS laptop that is powered by Intel HD Graphics 500 graphics card. The Acer laptop features an eMMC and 10h of battery life, while its body is made of Aluminium. Weighing only 1.4kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 13,900.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(89, 'acer', 'admin/image/acer-Acer Swift 3X.jpg', 'Acer Swift 3X Price List May, 2022 & Specs in Philippines', 'Acer�s Swift 3X is a Windows 10 laptop that is powered by Intel graphics card. The Acer laptop features an SSD and 14h of battery life, while its body is made of Aluminium. Weighing only 1.37kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 43,999.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(90, 'acer', 'admin/image/acer-Acer Chromebook R11.jpg', 'Acer Chromebook R11 Price List May, 2022 & Specs in Philippines', 'Acer�s Chromebook R11 is a Chrome OS laptop that is powered by Intel HD Graphics graphics card. The Acer laptop features an eMMC and 8h of battery life, while its body is made of Aluminium. Weighing only 1.25kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 22,000.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(91, 'acer', 'admin/image/acer-acer Swift 5 SF514-55TA.jpg', 'Acer Swift 5 SF514-55TA Price List May, 2022 & Specs in Philippines', 'acer�s Swift 5 SF514-55TA is a Windows 10 Home laptop that is powered by Intel Iris Xe Graphics graphics card. The acer laptop features an SSD and 17h of battery life, while its body is made of Aluminium. Weighing only 1kg, the acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this acer laptop and check out its specs!', '₱ 62,395.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(92, 'acer', 'admin/image/acer-Acer Aspire R13.jpg', 'Acer Aspire R13 Price List May, 2022 & Specs in Philippines', 'Acer�s Aspire R13 is a Windows 8 laptop that is powered by Intel graphics card. The Acer laptop features an SSD and 8h of battery life, while its body is made of Aluminium. Weighing only 1.5kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 27,160.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(93, 'acer', 'admin/image/acer-Acer ENDURO Urban N3.jpg', 'Acer ENDURO Urban N3 Price List May, 2022 & Specs in Philippines', 'Acer�s ENDURO Urban N3 is a Windows 10 Home laptop that is powered by Iris Xe Graphics graphics card. The Acer laptop features an SSD and 13h of battery life, while its body is made of Magnesium Alloy. Weighing only 1.85kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 72,536.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(95, 'acer', 'admin/image/acer-Acer ConceptD 3 Pro.jpg', 'Acer ConceptD 3 Pro Price List May, 2022 & Specs in Philippines', 'Acer�s ConceptD 3 Pro is a Windows 10 Pro laptop that is powered by NVIDIA� Quadro T1000 with 4 GB graphics card. The Acer laptop features an SSD and 14h of battery life, while its body is made of Aluminium. Weighing only 1.7kg, the Acer laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Acer laptop and check out its specs!', '₱ 107,498.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(96, 'dell', 'admin/image/dell-Dell XPS 13 9310.jpg', 'Dell XPS 13 9310 Price List May, 2022 & Specs in Philippines', 'Dell�s XPS 13 9310 is a Windows 10 Home laptop that is powered by Intel Iris Xe Graphics graphics card. The Dell laptop features an SSD and 14h of battery life, while its body is made of Aluminium. Weighing only 1.27kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 82,045.85', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(97, 'dell', 'admin/image/dell-DELL XPS 13 (2019).jpg', 'DELL XPS 13 (2019) 16GB Intel Core i7 512GB Price List May, 2022 & Specs in Philippines\r\n', 'DELL�s XPS 13 (2019) is a Windows 11 Home laptop that is powered by Intel UHD Graphics graphics card. The DELL laptop features an SSD and 11h of battery life, while its body is made of Aluminium. Weighing only 1.2kg, the DELL laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this DELL laptop and check out its specs!\r\n', '₱ 109,160.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(98, 'dell', 'admin/image/dell-DELL Inspiron 14.jpg', 'DELL Inspiron 14 2-in-1 Laptop Price List May, 2022 & Specs in Philippines', 'DELL�s Inspiron 14 2-in-1 Laptop is a Windows 10 laptop that is powered by Intel graphics card. The DELL laptop features an HDD and 9h of battery life, while its body is made of Plastic. Weighing only 2.3kg, the DELL laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this DELL laptop and check out its specs!', '₱ 39,008.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(99, 'dell', 'admin/image/dell-Dell G5 SE.jpg', 'Dell G5 SE Price List May, 2022 & Specs in Philippines', 'Dell�s G5 SE is a Windows 10 Home 64-bit English laptop that is powered by AMD Radeon� RX 5600M 6GB GDDR6 graphics card. The Dell laptop features an M.2 PCIe NVMe Solid State Drive and 10h of battery life, while its body is made of Plastic. Weighing only 2.5kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 52,500.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(100, 'dell', 'admin/image/dell-DELL XPS 15.jpg', 'DELL XPS 15 9500 Price List May, 2022 & Specs in Philippines', 'The DELL XPS 15 9500 is a 15.6\" IPS/IGZO display touchscreen laptop that operates on Windows 10 Home Single Language (64bit). It is powered by NVIDIA� GeForce� GTX 1650 Ti 4GB GDDR6 and is supported by 512GB SSD with up to 8GB RAM, while its battery life can last up to 25h. With DELL XPS 15 9500, you can stay productive and focus on your work; available with the cheapest price at PHP 179912 at iPrice today!', '₱ 179,912.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(101, 'dell', 'admin/image/dell-Dell Inspiron 15 5510.jpg', 'Dell Inspiron 15 5510 Price List May, 2022 & Specs in Philippines', 'Dell�s Inspiron 15 5510 is a Windows 10 Home laptop that is powered by Intel Iris Xe Graphics graphics card. The Dell laptop features an SSD and 4h of battery life, while its body is made of Aluminium. Weighing only 1.63kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 36,318.76', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(102, 'dell', 'admin/image/dell-Dell Inspiron 13 5000.jpg', 'Dell Inspiron 13 5000 Price List May, 2022 & Specs in Philippines', 'Dell�s Inspiron 13 5000 is a Windows 10 laptop that is powered by Intel HD Graphics 520 graphics card. The Dell laptop features an SSD and 3h of battery life, while its body is made of Plastic. Weighing only 1.68kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 64,928.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(103, 'dell', 'admin/image/dell-DELL XPS 15 16GB.jpg', 'DELL XPS 15 16GB Intel Core i7 512GB Price List May, 2022 & Specs in Philippines', 'The DELL XPS 15 is a 15\" IPS display touchscreen laptop that operates on Windows 10 Pro. It is powered by Nvidia GeForce GTX 1650 Ti and is supported by 512GB SSD with up to 16GB RAM, while its battery life can last up to 8h. With DELL XPS 15, you can stay productive and focus on your work; available with the cheapest price at PHP 159949 at iPrice today!', '₱ 159,949.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(104, 'dell', 'admin/image/dell-Dell Inspiron 14 5415.jpg', 'Dell Inspiron 14 5415 Price List May, 2022 & Specs in Philippines', 'Dell�s Inspiron 14 5415 is a Windows 10 Home Single laptop that is powered by NVIDIA� GeForce� MX350 graphics card. The Dell laptop features an SSD and 7h of battery life, while its body is made of Aluminium. Weighing only 1.46kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 38,490.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(105, 'dell', 'admin/image/dell-Dell XPS 13 9310 16GB.jpg', 'Dell XPS 13 9310 16GB Intel Core i5 512GB Price List May, 2022 & Specs in Philippines', 'Dell�s XPS 13 9310 is a Windows 10 Home laptop that is powered by Intel Iris Xe Graphics graphics card. The Dell laptop features an SSD and 14h of battery life, while its body is made of Aluminium. Weighing only 1.27kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 95,385.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(106, 'dell', 'admin/image/dell-Dell Latitude E6420.jpg', 'Dell Latitude E6420 Price List May, 2022 & Specs in Philippines', 'Dell�s Latitude E6420 is a Windows 10 laptop that is powered by Intel graphics card. The Dell laptop features an HDD and 8h of battery life, while its body is made of Steel. Weighing only 2.1kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 15,697.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(107, 'dell', 'admin/image/dell-Dell Inspiron Chromebook 11.jpg', 'Dell Inspiron Chromebook 11 2-in-1 Price List May, 2022 & Specs in Philippines', 'Dell�s Inspiron Chromebook 11 2-in-1 is a Unknown laptop that is powered by Intel graphics card. The Dell laptop features an eMMC and 42h of battery life, while its body is made of Aluminium. Weighing only 1.44kg, the Dell laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 11,950.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(108, 'dell', 'admin/image/dell-Dell Alienware M15.jpg', 'Dell Alienware M15 R4 Price List May, 2022 & Specs in Philippines', 'Dell�s Alienware M15 R4 is a Windows 11 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.38kg and is made from Aluminium. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 88,703.59', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(109, 'dell', 'admin/image/dell-DELL Latitude 7000 E7470.jpg', 'DELL Latitude 7000 E7470 Price List May, 2022 & Specs in Philippines', 'DELL�s Latitude 7000 E7470 is a Windows 7 laptop that is powered by Intel graphics card. The DELL laptop features an SSD and 10h of battery life, while its body is made of Magnesium Alloy. Weighing only 1.65kg, the DELL laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this DELL laptop and check out its specs!', '₱ 31,200.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(110, 'dell', 'admin/image/dell-Dell Alienware Area-51m 64GB.jpg', 'Dell Alienware Area-51m 64GB Intel Core i9 4TB Price List May, 2022 & Specs in Philippines', 'Dell�s Alienware Area-51m is a SSD laptop that features a Intel Core i9 that�s rated at 2.9GHz. In terms of graphics and display, it�s powered by a NVIDIA graphics card and has a screen resolution of 1920 x 1080pixels. It has a SSD, weighs only 4.7kg and is made from Aluminium. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 44,000.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(111, 'dell', 'admin/image/dell-Dell Alienware X15.jpg', 'Dell Alienware X15 Price List May, 2022 & Specs in Philippines', 'Dell�s Alienware X15 is a Windows 11 Home laptop. In terms of display, it has a screen resolution of 1920 x 1080pixels. It weighs only 2.36kg and is made from Magnesium Alloy. Scroll down below to compare the price of this Dell laptop and check out its specs!', '₱ 129,208.95', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(112, 'hp', 'admin/image/hp-HP 14s.jpg', 'HP 14s Price List May, 2022 & Specs in Philippines', 'HP�s 14s is a Windows 10 Home laptop that is powered by Intel� Iris� graphics graphics card. The HP laptop features an SSD and 2h of battery life, while its body is made of Aluminium. Weighing only 1.43kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 22,591.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(113, 'hp', 'admin/image/hp-HP Envy x360 13.jpg', 'HP Envy x360 13 Price List May, 2022 & Specs in Philippines', 'HP�s Envy x360 13 is a Windows 10 laptop that is powered by AMD Radeon Vega 8 Graphics graphics card. The HP laptop features an SSD and 5h of battery life, while its body is made of Aluminium. Weighing only 1.2kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 65,129.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(114, 'hp', 'admin/image/hp-HP ENVY 13.jpg', 'HP ENVY 13 Price List May, 2022 & Specs in Philippines', 'HP�s ENVY 13 is a Windows 7 laptop that is powered by Intel graphics card. The HP laptop features an HDD and 14h of battery life, while its body is made of Aluminium. Weighing only 1.2kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs! Read more', '₱ 49,990.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(115, 'hp', 'admin/image/hp-HP Omen 15.jpg', 'HP Omen 15 Price List May, 2022 & Specs in Philippines', 'Aside from its affordable price tag, the HP Omen boasts impressive specs and features you might need on a gaming laptop. Read more about the HP Omen below to find out.\r\n', '₱ 85,995.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(116, 'hp', 'admin/image/hp-HP EliteBook 840 G3.jpg', 'HP EliteBook 840 G3 Price List May, 2022 & Specs in Philippines', 'HP�s EliteBook 840 G3 is a Windows 7 laptop that is powered by Intel HD graphics card. The HP laptop features an SSD and 4h of battery life, while its body is made of Steel. Weighing only 1.5kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 81,578.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(117, 'hp', 'admin/image/hp-HP Envy X360 15-inch.jpg', 'HP Envy X360 15-inch Price List May, 2022 & Specs in Philippines', 'HP�s Envy X360 15-inch is a Windows 10 Home 64 laptop that is powered by AMD Radeon� Graphics graphics card. The HP laptop features an SSD and 13h of battery life, while its body is made of Aluminium. Weighing only 2.04kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 57,736.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(118, 'hp', 'admin/image/hp-HP Pavilion Aero 13.jpg', 'HP Pavilion Aero 13 Price List May, 2022 & Specs in Philippines', 'HP�s Pavilion Aero 13 is a Windows 10 Home laptop that is powered by AMD Radeon� Graphics graphics card. The HP laptop features an SSD and 10h of battery life, while its body is made of Aluminium. Weighing only 1.58kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 44,975.00 ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(119, 'hp', 'admin/image/hp-HP EliteBook 820 G1.jpg', 'HP EliteBook 820 G1 Price List May, 2022 & Specs in Philippines', 'HP�s EliteBook 820 G1 is a Windows 7 laptop that is powered by Intel HD graphics card. The HP laptop features an HDD and 4h of battery life, while its body is made of Steel. Weighing only 1.5kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 12,500.00  ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(120, 'hp', 'admin/image/hp-HP ProBook 430 G6.jpg', 'HP ProBook 430 G6 Price List May, 2022 & Specs in Philippines', 'HP�s ProBook 430 G6 is a Windows 10 laptop that is powered by Intel graphics card. The HP laptop features an SSD and 7h of battery life, while its body is made of Plastic. Weighing only 11.5kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 79,328.00 ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(121, 'hp', 'admin/image/hp-HP ProBook 650 G1.jpg', 'HP ProBook 650 G1 Price List May, 2022 & Specs in Philippines', 'The HP ProBook650 G1 uses the Windows. The laptop comes with a number of features such as the Intel Core i7, a processor speed of 2.5GHz, a RAM capacity of 2GB, a screen size of 14\", and it uses a premium LED screen as well.', '₱ 36,145.00 ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(122, 'hp', 'admin/image/hp-HP EliteBook Folio 1040 G3.jpg', 'HP EliteBook Folio 1040 G3 Price List May, 2022 & Specs in Philippines', 'Running on Windows 10, HP�s EliteBook Folio 1040 G3 has a screen resolution of 1920 x 1080pixels. Weighs only 1.43kg, this HP laptop has a SSD, and is made from Aluminium. Scroll down to view the full specs of HP EliteBook Folio 1040 G3 now!', '₱ 7,373.80  ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(123, 'hp', 'admin/image/hp-HP Elite Dragonfly.jpg', 'HP Elite Dragonfly Price List May, 2022 & Specs in Philippines', 'HP�s Elite Dragonfly is a Windows 10 Home laptop that is powered by Intel UHD Graphics 620 graphics card. The HP laptop features an SSD and 14h of battery life, while its body is made of Aluminium. Weighing only 0.99kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 35,000.00   ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(124, 'hp', 'admin/image/hp-HP Pavilion 15 Silver.jpg', 'HP Pavilion 15 Silver Intel Core i5-8250U 1TB / 8GB Price List May, 2022 & Specs in Philippines', 'The HP Pavilion 15 is a 15.6\" LED display touchscreen laptop that operates on Windows 10. It is powered by NVIDIA and is supported by 512GB SSD with up to 4GB RAM, while its battery life can last up to 14h. With HP Pavilion 15, you can stay productive and focus on your work; available with the cheapest price at PHP 57024 at iPrice today!', '₱ 57,024.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(125, 'hp', 'admin/image/hp-HP Pavilion 15 Blue.jpg', 'HP Pavilion 15 Blue AMD Ryzen 5 4500U 512GB / 8GB Price List May, 2022 & Specs in Philippines', 'The HP Pavilion 15 is a 15.6\" LED display touchscreen laptop that operates on Windows 10. It is powered by NVIDIA and is supported by 512GB SSD with up to 4GB RAM, while its battery life can last up to 14h. With HP Pavilion 15, you can stay productive and focus on your work; available with the cheapest price at PHP 48120 at iPrice today!', '₱ 48,120.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(126, 'hp', 'admin/image/hp-HP EliteBook 820 G2.jpg', 'HP EliteBook 820 G2 Price List May, 2022 & Specs in Philippines', 'HP�s EliteBook 820 G2 is a Windows 7 laptop that is powered by Intel graphics card. The HP laptop features an SSD and 8h of battery life, while its body is made of Aluminium. Weighing only 1.34kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 25,751.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(127, 'hp', 'admin/image/hp-HP ProBook 455 G2.jpg', 'HP ProBook 455 G2 Price List May, 2022 & Specs in Philippines', 'HP�s ProBook 455 G2 is a Windows laptop that is powered by AMD Radeon� R6 graphics card. The HP laptop features an SATA and 7h of battery life, while its body is made of Aluminium. Weighing only 0.28kg, the HP laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this HP laptop and check out its specs!', '₱ 14,999.00', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(128, 'lenovo', 'admin/image/lenovo-Lenovo IdeaPad Flex 5.jpg', 'Lenovo IdeaPad Flex 5 Price List May, 2022 & Specs in Philippines', 'Lenovo�s IdeaPad Flex 5 is a Windows 10 laptop that is powered by AMD Integrated Graphics graphics card. The Lenovo laptop features an SSD and 12h of battery life, while its body is made of Aluminium. Weighing only 1.6kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 33,560.00 ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(129, 'lenovo', 'admin/image/lenovo-Lenovo IdeaPad Slim 3.jpg', 'Lenovo IdeaPad Slim 3 15-inch Price List May, 2022 & Specs in Philippines', 'Lenovo�s IdeaPad Slim 3 15-inch is a Windows 10 laptop that is powered by AMD Radeon� Graphics graphics card. The Lenovo laptop features an SSD and 7.5h of battery life, while its body is made of Aluminium. Weighing only 1.85kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs! Read more', '₱ 21,182.00 ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(130, 'lenovo', 'admin/image/lenovo-Lenovo Legion 5 Pro.jpg', 'Lenovo Legion 5 Pro Price List May, 2022 & Specs in Philippines', 'Lenovo�s Legion 5 Pro is a Windows 10 Pro laptop that is powered by NVIDIA�GeForce RTX� 3070 graphics card. The Lenovo laptop features an SSD and 16h of battery life, while its body is made of Aluminium. Weighing only 2.54kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!\r\n', '₱ 75,056.00  ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(131, 'lenovo', 'admin/image/lenovo-Lenovo Ideapad Ideapad 5.jpg', 'Lenovo Ideapad Ideapad 5 Price List May, 2022 & Specs in Philippines', 'The Lenovo Ideapad Ideapad 5 is a 14\" IPS display touchscreen laptop that operates on Windows 10 Home. It is powered by AMD� Ryzen� and is supported by 512GB SSD with up to 16GB RAM, while its battery life can last up to 17h. With Lenovo Ideapad Ideapad 5, you can stay productive and focus on your work; available with the cheapest price at PHP 15000 at iPrice today!', '₱ 15,000.00   ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(132, 'lenovo', 'admin/image/lenovo-Lenovo Ideapad 320.jpg', 'Lenovo Ideapad 320 Price List May, 2022 & Specs in Philippines', 'The Lenovo Ideapad 320 is a 15\" IPS display touchscreen laptop that operates on Windows 10 Home. It is powered by AMD and is supported by 1000GB HDD with up to 4GB RAM, while its battery life can last up to 6h. With Lenovo Ideapad 320, you can stay productive and focus on your work; available with the cheapest price at PHP 19990 at iPrice today!', '₱ 19,990.00    ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(133, 'lenovo', 'admin/image/lenovo-Lenovo Chromebook C330.jpg', 'Lenovo Chromebook C330 Price List May, 2022 & Specs in Philippines', 'Lenovo�s Chromebook C330 is a Chrome OS laptop that is powered by Integrated PowerVR GX6250 Graphics graphics card. The Lenovo laptop features an eMMC and 10h of battery life, while its body is made of Plastic. Weighing only 1.2kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs! Read more', '₱ 12,982.32     ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(134, 'lenovo', 'admin/image/lenovo-Lenovo Yoga 9i.jpg', 'Lenovo Yoga 9i Price List May, 2022 & Specs in Philippines', 'Lenovo�s Yoga 9i is a Windows 10 Home Single Language 64 laptop that is powered by Intel Iris Xe graphics card. The Lenovo laptop features an SSD and 17h of battery life, while its body is made of Aluminium. Weighing only 1.37kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 104,208.00 ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(135, 'lenovo', 'admin/image/lenovo-Lenovo IdeaPad 100s.jpg', 'Lenovo IdeaPad 100s Price List May, 2022 & Specs in Philippines', 'Battery life is one of the utmost important things when considering the purchase of a new netbook. Having being made compact and mobile enough to be able to be used anywhere, you would need that long battery lifespan. By that, Lenovo brings out the Ideapad 100s. Check out the offers below or click here to read more about this netbook.', '₱ 34,112.00  ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(136, 'lenovo', 'admin/image/lenovo-Lenovo ThinkPad E560.jpg', 'Lenovo ThinkPad E560 Price List May, 2022 & Specs in Philippines', 'Lenovo�s ThinkPad E560 is a Windows 7 laptop that is powered by AMD Radeon� R7 graphics card. The Lenovo laptop features an HDD and 9h of battery life, while its body is made of Carbon Fiber. Weighing only 2.4kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 21,500.00  ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(137, 'lenovo', 'admin/image/lenovo-Lenovo ThinkPad Edge E14.jpg', 'Lenovo ThinkPad Edge E14 Gen 2 Price List May, 2022 & Specs in Philippines', 'Lenovo�s ThinkPad Edge E14 Gen 2 is a 10 Pro laptop that is powered by Integrated AMD graphics graphics card. The Lenovo laptop features an SSD-1 and 13h of battery life, while its body is made of Aluminium. Weighing only 1.59kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 50,895.00   ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(138, 'lenovo', 'admin/image/lenovo-Lenovo ThinkPad X1.jpg', 'Lenovo ThinkPad X1 Nano Price List May, 2022 & Specs in Philippines', 'Running on Windows 10 Home, Lenovo�s ThinkPad X1 Nano has a screen resolution of 2160 x 1350pixels. Weighs only 4.3kg, this Lenovo laptop has a SSD, and is made from Plastic. Scroll down to view the full specs of Lenovo ThinkPad X1 Nano now!', '₱ 80,850.00    ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(140, 'lenovo', 'admin/image/lenovo-Lenovo ThinkPad Yoga X1.jpg', 'Lenovo ThinkPad Yoga X1 Price List May, 2022 & Specs in Philippines', 'Running on Windows 10 Pro, Lenovo�s ThinkPad Yoga X1 has a screen resolution of 1920 x 1080pixels. Weighs only 1.36kg, this Lenovo laptop has a SSD, and is made from Carbon Fiber. Scroll down to view the full specs of Lenovo ThinkPad Yoga X1 now!', '₱ 29,388.00     ', '', '', '', '2022-05-12 19:15:56', NULL, NULL);
INSERT INTO `tblproduct` (`id`, `brand`, `product_image`, `product_name`, `product_description`, `price`, `customer`, `product_id_number`, `product_status`, `date_of_purchase`, `payment_method`, `shippingfee`) VALUES
(141, 'lenovo', 'admin/image/lenovo-Lenovo ThinkPad X270.jpg', 'Lenovo ThinkPad X270 Price List May, 2022 & Specs in Philippines', 'Running on Windows 10, Lenovo�s ThinkPad X270 has a screen resolution of 1366 x 768pixels. Weighs only 1.59kg, this Lenovo laptop has a SSD, and is made from Plastic. Scroll down to view the full specs of Lenovo ThinkPad X270 now!', '₱ 64,486.00      ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(142, 'lenovo', 'admin/image/lenovo-Lenovo ThinkPad T470.jpg', 'Lenovo ThinkPad T470 Price List May, 2022 & Specs in Philippines', 'Lenovo�s ThinkPad T470 is a Windows 10 Pro laptop that is powered by Intel HD Graphics 620 graphics card. The Lenovo laptop features an SSD and 13.9h of battery life, while its body is made of Plastic. Weighing only 1.65kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 51,608.00       ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(143, 'lenovo', 'admin/image/lenovo-Lenovo Ideapad S145.jpg', 'Lenovo Ideapad S145 Grey Intel Pentium Gold 128GB / 4GB Price List May, 2022 & Specs in Philippines', 'Lenovo�s Ideapad S145 is a Windows 10 Home laptop that is powered by Intel� UHD Graphics 610 graphics card. The Lenovo laptop features an SSD and 6h of battery life, while its body is made of Aluminium. Weighing only 1.85kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 30,360.00       ', '', '', '', '2022-05-12 19:15:56', NULL, NULL),
(311, NULL, 'admin/image/asus-Asus Zenbook 14 Ultrabook.jpg', 'Asus Zenbook 14 Ultrabook Price List May, 2022 & Specs in Philippines', 'Running on Windows 10 Home, Windows 10 Pro, Asus�s Zenbook 14 Ultrabook has a screen resolution of 1080 x 1920pixels. Weighs only 1.39kg, this Asus laptop has a SSD, and is made from Steel. Scroll down to view the full specs of Asus Zenbook 14 Ultrabook now!', '₱ 49,990.00', '', NULL, 'parcel', '2022-05-15 09:50:00', 'Cash On delivery [COD]', NULL),
(313, NULL, 'admin/image/uploaded_bbfa4bd7e0c7b1b6a84b0425313c757c.jpg', 'Lenovo IdeaPad 3 14 Price List May, 2022 & Specs in Philippines', 'Lenovo’s IdeaPad 3 14 is a Windows 10 Home laptop that is powered by Intel UHD G1 graphics card. The Lenovo laptop features an SSD and 4h of battery life, while its body is made of Plastic. Weighing only 1.6kg, the Lenovo laptop is ultra-portable and convenient to carry around with you. Scroll down below to compare the price of this Lenovo laptop and check out its specs!', '₱ 23,478.00', NULL, NULL, 'parcel', '2022-05-15 09:50:16', 'Credit Card', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--
-- Creation: May 13, 2022 at 02:18 AM
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `displayed_pic` varchar(255) DEFAULT NULL,
  `person_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `user_address` varchar(255) DEFAULT NULL,
  `phone_number` varchar(255) DEFAULT NULL,
  `shop_name` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `birthdate` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

--
-- RELATIONSHIPS FOR TABLE `users`:
--

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `created_at`, `displayed_pic`, `person_name`, `email`, `user_address`, `phone_number`, `shop_name`, `gender`, `birthdate`) VALUES
(1, 'administrator', '$2y$10$OI66zuLfyHbKji156VcG6.HqtxgxtKIZbKPtPBh8Kp0d5AH2zlhbW', '2022-04-29 12:45:28', 'admin/image/1584026003710.png', 'jhon carlo laspona Loguiber', 'jcarlo.loguiber@gmail.com', 'purok 3 mipangi nabunturan davao de oro', '+639514567270', '', 'Male', '2002-06-06');
COMMIT;
